### ISSUE TITLE
Questions regarding materials to build the sensor.

### ISSUE THREAD

**Issue by ErickRosete** [facebookresearch/digit-design#12]
1.- According to the Quick Start Guide the gel acrylic window is cut from a sheet of 4 mm thick optically clear acrylic, but checking the step files available I found that the thickness of the 3D model is 6.15 mm, which is the appropriate dimension?
2.- According to the Quick Start Guide Smooth-On Solaris the shore hardness is 10A, but the only product available in the official webpage https://www.smooth-on.com/products/solaris/  says the shore hardness is 15A, is it a different product?

**Comment by AlphaBetaPhi** [comment]
@ErickRosete, thank you for your interest and questions.

1. This can be cut from a 6 mm sheet of optically clear acrylic (will update this in the guide), in either case, this can be built with whichever size between 4-6.2 mm acrylic panel is available.
2. You may order the product shore 15A product from Smooth-On, we have found through internal testing that the gel design results in shore hardness 10 using the shore 15A product. Additionally, you may use the Smooth-On Slacker product to change shore hardness.

We will add additional notes to the gel instructions to address these issues and provide some insight onto changing gel parameters for end applications.
