### ISSUE TITLE
Markers in gel: getting "actual" force estimates

### ISSUE THREAD

**Issue by vincentmaye** [facebookresearch/digit-design#16]
Hey Digit-Team,

fantastic work thanks for making it available!

I was wondering if you could share your experiences with adding markers / reference particles into the gel to estimate forces based on marker displacements, since I saw one elastomer with markers in the paper but no further explanation? 

1. How much does this complicate the manufacturing process and
2. how accurate could the estimated forces be?

Thanks!

**Comment by AlphaBetaPhi** [comment]
Hi @vincentmaye,

There are a number of methods to add markers on the gels,

- print them on with a UV printer (or any other suitable method) and then cover with the white image transfer layer
- laser etch them onto the surface of the white image transfer layer
