### ISSUE TITLE
Airbrush

### ISSUE THREAD

**Issue by luarss** [facebookresearch/digit-design#17]
Hi,

First of all, thanks for making this sensor open-source! I am looking to purchase the items and am not sure what sort of airbrush is required for the mold. If anyone could let me know that would be great!

**Comment by AlphaBetaPhi** [comment]
Hi @luarss,

Thank you for your interest in the project.

We recommend the following: Iwata-Medea Eclipse HP CS Dual Action Airbrush Gun / Gravity Feed.

**Comment by luarss** [comment]
Wow that is expensive. Do you have any recommendations as to the tip size we should use for the spraying?
