### ISSUE TITLE
Sizes of screws do not match between main and back cases

### ISSUE THREAD

**Issue by gabrielecaddeo** [facebookresearch/digit-design#21]
Hi everyone,

thank you for the great sensor design that you made publicly available.

Me and my team reproduced the Digit and we noticed some incoherencies in the design of the mechanical components. We were wondering if the provided design files are correct and, in this case, we would like to highlight some issues we encountered.

The back case and the main case are kept together by means of screws. In the STL files of the backhousing and of the main housing (both with or without snap) it is possible to see that the diameter of the screws does not match. The right screw for the back case is an M2 (and also for the main PCB), while the diameter of the main case suggests the use of an M4.
![screws](https://user-images.githubusercontent.com/49904924/127336841-6995507c-5587-4fbc-ad37-36b446347446.PNG)

Hence, we were wondering if that is normal or if there are some inconsistencies in the files in the git repository.

Thanks!

**Comment by AlphaBetaPhi** [comment]
Hi @gabrielecaddeo,

Thank you for raising this issue. An update with the latest revision will be pushed to the github repository. The designs are identical in terms of size but the mounting features are slightly different.

**Comment by gabrielecaddeo** [comment]
Hi @AlphaBetaPhi, 

Thanks for the answer. Looking forward to see the latest revision.

Thank you again.

**Comment by AlphaBetaPhi** [comment]
Hi @gabrielecaddeo, 

The latest mechanical revision has been pushed. Note, the new design contains open holes on the back of the center body enclosure. These will need to be covered by a black tape.
