### ISSUE TITLE
type of the Optically Clear Adhesive

### ISSUE THREAD

**Issue by lianghongzhuo** [facebookresearch/digit-design#22]
Hi, thank you very much for your great work and sharing.
Just to be sure, is the link below exactly what you used to glue the sensor?
https://www.amazon.de/SilPoxy-Silikon-Kleber-3-g-Tube/dp/B00IRC1YI0
https://www.smooth-on.com/products/sil-poxy/
Because I didn't see in the instruction that this type of glue is optically clear.
Thanks in advance!

**Comment by AlphaBetaPhi** [comment]
Hi @lianghongzhuo,

This is an acceptable glue to use. The best technique we found is to place a pea sized blob in the center of the acrylic window and then place the silicone gel on top spreading out the glue from the center until it ejects from the sides. This prevents bubbles or streak lines when the glue dries.
