### ISSUE TITLE
attaching digit to robotiq 2f-85 gripper

### ISSUE THREAD

**Issue by stoic-roboticist** [facebookresearch/digit-design#32]
Hi,

I would like to attach the digit sensor to a Robotiq 2F-85 gripper. I printed the supplied adapters, however, I couldn't find anywhere in the documentation of what bolts to use to attach the sensor to the printed adapter? also the holes on the bottom of the digit don't seem threaded, so how can you securely attach the sensor to the adapter?

Thanks in advance for your help.

**Comment by AlphaBetaPhi** [comment]
Hi @stoic-roboticist,

The Robotiq 2F-85 uses an M5 screw with the default grippers. The same screw can be used with the DIGIT adapter, which is attached to the DIGIT with an M2 screw (https://www.mcmaster.com/91292A005/ or longer lengths). The screws self tap into the plastic.
