### ISSUE TITLE
About SMT files

### ISSUE THREAD

**Issue by chenwh14** [facebookresearch/digit-design#4]
Hello,

Thank you for your excellent work!

Could you please export a 'pick and place' file for each PCB design from your original project? It will be helpful for automated SMT component placement, reducing manual work. 

Thanks again!

**Comment by AlphaBetaPhi** [comment]
Hello @chenwh14,

Thank you for your interest! The files have beed added.

**Comment by robertocalandra** [comment]
Closing the issue. Feel free to re-open it if the answer is not of your satisfaction.
