### ISSUE TITLE
DIGIT Pinki Dataset

### ISSUE THREAD

**Issue by abtabrizi** [facebookresearch/digit-design#42]
Hi all,

Your DIGIT Pinki paper is very impressive. @JuliaDi @AlphaBetaPhi @robertocalandra 
Will the datasets used for the force estimation (Normal/Shear) be made publicly available?

**Comment by JuliaDi** [comment]
Hi @abtabrizi, thanks for your comment. Unfortunately at this time we will not be providing the datasets for the force estimation (Normal/Shear) to the public, but we will update the repo in the future if that policy changes.
