### ISSUE TITLE
CC-BY-NC license

### ISSUE THREAD

**Issue by nouyang** [facebookresearch/digit-design#6]
I wanted to confirm my understanding of the license: that the CC-BY-non-commercial applies to the design files themselves and not the manufactured objects (per [explanation](https://www.oshwa.org/sharing-best-practices/) from the open source hardware association).

I ask because I would like to crowdsupply the circuitboards (for economics of scale* and given that I really only want one device). The easiest way would be to make a bulk purchase and then sell it to other researchers. I want to check that I won't run into issues if e.g. I need to add on shipping fees for other researchers.

```
* There is a 17% price break per unit, between Qty 10 and Qty 20, so I would likely aim for a qty 20 group order:

Qty 10 | 20 | 30 | 40 | 55
102.80 | 87.80 | 84.07 | 81.93 | 79.40
```

Thanks!

**Comment by robertocalandra** [comment]
I am afraid that we are not lawyers and cannot provide legal advice on your specific use case here.
