### ISSUE TITLE
Layout of LED

### ISSUE THREAD

**Issue by lzyplayer** [facebookresearch/digit-design#7]
Hi! 
Thanks for opening source such great work!

I'm wondering how the rgb light layout on the surface is designed.
![image](https://user-images.githubusercontent.com/20348451/86082036-7279d000-bac9-11ea-9578-f090164fe576.png)
It seems blue light cover the whole image, while red and green only cross a little compared with gelsight LED layout.(below)
![image](https://user-images.githubusercontent.com/20348451/86082342-16fc1200-baca-11ea-8f7c-757698d8a90a.png)
Will it be a problem on reconstructing the surface?

Thanks for any reply!

**Comment by lzyplayer** [comment]
Another question, 
![image](https://user-images.githubusercontent.com/20348451/86219248-80f0e600-bbb4-11ea-84df-fe7e896c00e4.png)
the quantities doesn't match current designator. Also, it seems 5 LED is required accroding to [Digit Flex Schematic - rev 2020-1.pdf](https://github.com/facebookresearch/digit-design/blob/master/hardware/Digit%20Flex%20Schematic%20-%20rev%202020-1.pdf)
Thanks for any reply!

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer,

Thank you for your feedback and interest.

Up to 4 LED's may be included, however, for DIGIT we only populate D1, D2, D3. The compressed release file specifies the populated components in "digit_flex_smt_xy.txt".

I will update the BOM PDF to state that these are optional.

There will be an update to this issue regarding your the initial comment about the lighting configuration.

**Comment by lzyplayer** [comment]
Thanks for your quick reply! That solve my latter question. 
Really looking forword to the upcomming update!

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer,

The DIGIT was designed to resemble that of a finger tip. Two LED's (red and green) are offset by 45deg from the center, and the blue LED is directly in the center. I do believe it might impact 3D reconstruction performance but this is something we do not have any numbers to verify this.

**Comment by lzyplayer** [comment]
Thanks for your kindly reply! I 'll try some reconstruction work on current DIGIT sensor and share what I found.
