### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by ucabwl2** [facebookresearch/digit-design#8]
Hi 

This sensor is awesome. I wonder is there any dataset available online? Thanks.

**Comment by robertocalandra** [comment]
Hi ucabwl2,
Thanks for the compliment.
We currently don't have any public dataset collected using DIGIT.
What dataset would you be interested in having in the future?

**Comment by ucabwl2** [comment]
Hi 
Thanks for your reply. Currently, I'm interested in the dataset like the one collected by GelSight.
https://sites.google.com/view/the-feeling-of-success/

**Comment by robertocalandra** [comment]
Ok that's useful feedback. Thanks :)
