### ISSUE TITLE
Firmware update: idVendor correct?

### ISSUE THREAD

**Issue by b4be1** [facebookresearch/digit-design#9]
The ID that I get when connecting Digit via USB is different from the one in https://github.com/facebookresearch/digit-design/blob/master/firmware/digit-programmer/programmer.yaml, which is `2833:0209 Oculus VR, Inc.`

The ID that I get is `0403:0fde Future Technology Devices International, Ltd`. Is this important? I have not flashed the firmware yet. When I execute `dfu-util -l`, I get

    `Found DFU: [0403:0fde] ver=2300, devnum=6, cfg=1, intf=0, path="1-12", alt=0, name="UNKNOWN", serial="00000000"`

**Comment by AlphaBetaPhi** [comment]
Hi @b4be1,

On a fresh build, the FTDI DFU is used with vid/pid `0403:0fde`. Currently, the vid/pid values inside `programmer.yaml` are not enforced. Upon programming the binary file, the device will first boot into DFU mode for 3 seconds with `0403:0fde` and then enumerate with `2833:0209`.
